
services:
  web_api:
    build: .
    volumes:
      - ./:/code
      - ./db:/data
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=sqlite:///data/todolist.db
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]

volumes:
  db:
